# Generated by Django 4.2.26 on 2025-11-12 15:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sops', '0002_sop_duration_seconds_sop_external_url_sop_media_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sop',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='sop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
