# Generated by Django 5.2.8 on 2025-11-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sops', '0003_alter_sop_options_sop_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sop',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
