# Generated by Django 5.2.7 on 2025-10-21 16:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SOP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('version_major', models.PositiveIntegerField(default=1)),
                ('version_minor', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('review', 'review'), ('published', 'published'), ('retired', 'retired')], default='draft', max_length=20)),
                ('content', models.JSONField(default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('change_note', models.TextField(blank=True, default='')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.org')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sop_publishers', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sop_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('org', 'code', 'version_major', 'version_minor')},
            },
        ),
    ]
