# Generated by Django 5.2.7 on 2025-10-23 14:32

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sops", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sop",
            name="duration_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sop",
            name="external_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sop",
            name="media_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="sops/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "mkv", "pdf", "pptx", "ppt"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="sop",
            name="media_type",
            field=models.CharField(
                choices=[("video", "video"), ("pdf", "pdf"), ("pptx", "pptx"), ("link", "link")],
                default="pdf",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="sop",
            name="pages",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sop",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="sops/thumbs/"),
        ),
        migrations.CreateModel(
            name="SOPView",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("seconds_viewed", models.PositiveIntegerField(default=0)),
                ("pages_viewed", models.PositiveIntegerField(default=0)),
                ("progress", models.FloatField(default=0.0)),
                ("completed", models.BooleanField(default=False)),
                ("last_heartbeat", models.DateTimeField(auto_now=True)),
                (
                    "sop",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="views", to="sops.sop"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sop_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("sop", "user")},
            },
        ),
    ]
