# Generated by Django 4.2.26 on 2025-11-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_alter_moduleattempt_options_moduleattempt_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleattempt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
