# Generated by Django 4.2.26 on 2025-11-12 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0009_alter_moduleattempt_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recertrequirement',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recertrequirement',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='recertrequirement',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recert_requirements', to='accounts.org'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recertrequirement',
            name='reason',
            field=models.CharField(blank=True, choices=[('expiry', 'expiry'), ('sop_major_update', 'sop_major_update')], max_length=30),
        ),
        migrations.AlterField(
            model_name='recertrequirement',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recert_requirements', to='learning.skill'),
        ),
        migrations.AlterField(
            model_name='recertrequirement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recert_requirements', to=settings.AUTH_USER_MODEL),
        ),
    ]
