# Generated by Django 4.2.26 on 2025-11-13 16:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sops', '0004_sop_active'),
        ('learning', '0010_recertrequirement_due_at_recertrequirement_meta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recertrequirement',
            options={'ordering': ['due_date', 'id']},
        ),
        migrations.RenameField(
            model_name='recertrequirement',
            old_name='due_at',
            new_name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='recertrequirement',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='recertrequirement',
            name='resolved',
        ),
        migrations.AddField(
            model_name='recertrequirement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recertrequirement',
            name='sop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recert_requirements', to='sops.sop'),
        ),
        migrations.AlterField(
            model_name='recertrequirement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recertrequirement',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recert_requirements', to='learning.skill'),
        ),
    ]
