# Generated by Django 4.2.26 on 2025-11-13 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('sops', '0004_sop_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0011_alter_recertrequirement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recertrequirement',
            options={'ordering': ['due_at', 'due_date', 'id']},
        ),
        migrations.RenameField(
            model_name='recertrequirement',
            old_name='resolved_at',
            new_name='due_at',
        ),
        migrations.RemoveField(
            model_name='recertrequirement',
            name='created_at',
        ),
        migrations.AddField(
            model_name='recertrequirement',
            name='reason',
            field=models.CharField(blank=True, help_text="Short explanation like 'expiry' or 'SOP major update'", max_length=40),
        ),
        migrations.AddField(
            model_name='recertrequirement',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recertrequirement',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recertrequirement',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.org'),
        ),
        migrations.AlterField(
            model_name='recertrequirement',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.skill'),
        ),
        migrations.AlterField(
            model_name='recertrequirement',
            name='sop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sops.sop'),
        ),
        migrations.AlterField(
            model_name='recertrequirement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
