# Generated by Django 4.2.26 on 2025-11-16 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('learning', '0012_alter_recertrequirement_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('job_role_label', models.CharField(blank=True, max_length=200)),
                ('department_label', models.CharField(blank=True, max_length=200)),
                ('level_label', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_training_pathways', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_pathways', to='accounts.org')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingPathwayItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sop_label', models.CharField(blank=True, max_length=255)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_pathway_items', to='learning.module')),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='learning.trainingpathway')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_pathway_items', to='learning.skill')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
