# Generated by Django 4.2.26 on 2025-11-17 22:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_trainingpathway_trainingpathwayitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='feedback_mode',
            field=models.CharField(choices=[('immediate', 'Immediate after each question'), ('end', 'Only at the end of the quiz'), ('none', 'No feedback'), ('mixed', 'Mixed: single/truefalse=immediate, multi-select=end')], default='end', max_length=20),
        ),
        migrations.CreateModel(
            name='ModuleAttemptQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selection_history', models.JSONField(blank=True, default=list)),
                ('final_choices', models.JSONField(blank=True, default=list)),
                ('correct', models.BooleanField(default=False)),
                ('points_awarded', models.IntegerField(default=0)),
                ('time_taken', models.FloatField(default=0.0)),
                ('changed_answer', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_questions', to='learning.moduleattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_instances', to='learning.question')),
            ],
        ),
    ]
