# Generated by Django 4.2.26 on 2025-11-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_module_feedback_mode_moduleattemptquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='feedback_mode',
            field=models.CharField(choices=[('immediate', 'Immediate after each question'), ('end', 'Only at the end of the quiz'), ('none', 'No feedback'), ('mixed', 'Mixed: single/truefalse=immediate, multi-select=end')], default='end', help_text='Controls when the learner sees feedback for quiz questions.', max_length=20),
        ),
    ]
