# Generated by Django 5.2.7 on 2025-10-21 16:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('sops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.org')),
            ],
            options={
                'unique_together': {('org', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('difficulty', models.PositiveSmallIntegerField(default=2)),
                ('passing_score', models.PositiveSmallIntegerField(default=80)),
                ('active', models.BooleanField(default=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.org')),
                ('sop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sops.sop')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('risk_level', models.CharField(choices=[('low', 'low'), ('med', 'med'), ('high', 'high')], default='med', max_length=10)),
                ('valid_for_days', models.PositiveIntegerField(default=365)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.org')),
            ],
            options={
                'unique_together': {('org', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RecertRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_date', models.DateField()),
                ('reason', models.CharField(choices=[('expiry', 'expiry'), ('sop_major_update', 'sop_major_update')], max_length=30)),
                ('resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.skill')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.skill'),
        ),
        migrations.CreateModel(
            name='SupervisorSignoff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.skill')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signer', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='XPEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('module_pass', 'module_pass'), ('quiz', 'quiz'), ('streak', 'streak'), ('supervisor_signoff', 'supervisor_signoff'), ('evidence', 'evidence')], max_length=40)),
                ('amount', models.PositiveIntegerField()),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.org')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoleSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.jobrole')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.skill')),
            ],
            options={
                'unique_together': {('role', 'skill')},
            },
        ),
    ]
