# Generated by Django 5.2.7 on 2025-10-22 13:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelDef',
            fields=[
                ('level', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('total_xp', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('rule_type', models.CharField(choices=[('overall_xp_at_least', 'overall_xp_at_least'), ('skill_xp_at_least', 'skill_xp_at_least'), ('signoffs_at_least', 'signoffs_at_least')], max_length=40)),
                ('value', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(blank=True, default='', max_length=200)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.org')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.skill')),
            ],
            options={
                'unique_together': {('org', 'code')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-awarded_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
