# Generated by Django 5.2.7 on 2025-10-23 14:32

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0005_badge_department_badge_team_alter_badge_rule_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moduleattempt",
            name="answers",
        ),
        migrations.RemoveField(
            model_name="moduleattempt",
            name="completed_at",
        ),
        migrations.RemoveField(
            model_name="moduleattempt",
            name="module",
        ),
        migrations.RemoveField(
            model_name="moduleattempt",
            name="passed",
        ),
        migrations.RemoveField(
            model_name="moduleattempt",
            name="score",
        ),
        migrations.RemoveField(
            model_name="moduleattempt",
            name="started_at",
        ),
        migrations.RemoveField(
            model_name="moduleattempt",
            name="user",
        ),
        migrations.AddField(
            model_name="module",
            name="negative_marking",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="module",
            name="pass_mark",
            field=models.PositiveSmallIntegerField(default=80),
        ),
        migrations.AddField(
            model_name="module",
            name="question_pool_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="module",
            name="require_viewed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="module",
            name="shuffle_choices",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="module",
            name="shuffle_questions",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="moduleattempt",
            name="choice_order",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="moduleattempt",
            name="presented_questions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="moduleattempt",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "qtype",
                    models.CharField(
                        choices=[("single", "single"), ("multi", "multi"), ("truefalse", "truefalse")],
                        default="single",
                        max_length=10,
                    ),
                ),
                ("text", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("points", models.PositiveIntegerField(default=1)),
                ("explanation", models.TextField(blank=True, default="")),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="questions", to="learning.module"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("text", models.CharField(max_length=400)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="choices", to="learning.question"
                    ),
                ),
            ],
        ),
    ]
