# Generated by Django 5.2.7 on 2025-10-23 18:05

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0007_init_moduleattempt_fix"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="moduleattempt",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="moduleattempt",
            name="answers",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="moduleattempt",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="moduleattempt",
            name="module",
            field=models.ForeignKey(
                default="2025-10-23 00:00:00",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="learning.module",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="moduleattempt",
            name="passed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="moduleattempt",
            name="score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="moduleattempt",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="moduleattempt",
            name="user",
            field=models.ForeignKey(
                default=uuid.uuid4,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="module_attempts",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
